export const teams = [
    {name: "Sevilla", imgUrl: `${import.meta.env.BASE_URL}sevilla.svg`, power: 73, stadium: "Рамон Санчес Писхуан", played: true},
    {name: "Barcelona", imgUrl: `${import.meta.env.BASE_URL}barcelona.svg`, power: 87, stadium: "Камп Ноу", played: false},
    {name: "Atlético Madrid", imgUrl: `${import.meta.env.BASE_URL}atletico-madrid.svg`, power: 85, stadium: "Метрополитано", played: false},
    {name: "Athletic Club", imgUrl: `${import.meta.env.BASE_URL}athletic-club.svg`, power: 78, stadium: "Сан-Мамес", played: false},
    {name: "Villarreal", imgUrl: `${import.meta.env.BASE_URL}villarreal.svg`, power: 76, stadium: "Эстадио де ла Керамика", played: false},
    {name: "Real Sociedad", imgUrl: `${import.meta.env.BASE_URL}real-sociedad.svg`, power: 78, stadium: "Аноэта", played: false},
    {name: "Real Betis", imgUrl: `${import.meta.env.BASE_URL}real-betis.svg`, power: 81, stadium: "Бенито Вильямарин", played: false},
    {name: "Valencia", imgUrl: `${import.meta.env.BASE_URL}valencia.svg`, power: 74, stadium: "Месталья", played: false},
    {name: "Celta Vigo", imgUrl: `${import.meta.env.BASE_URL}celta.svg`, power: 71, stadium: "Балаидос", played: false},
    {name: "Osasuna", imgUrl: `${import.meta.env.BASE_URL}osasuna.svg`, power: 69, stadium: "Эль Садар", played: false},
    {name: "Espanyol", imgUrl: `${import.meta.env.BASE_URL}espanyol.svg`, power: 67, stadium: "RCDE Стэдиум", played: false},
    {name: "Levante", imgUrl: `${import.meta.env.BASE_URL}levante.svg`, power: 68, stadium: "Сьюдад де Валенсия", played: false},
    {name: "Deportivo LaCoruña", imgUrl: `${import.meta.env.BASE_URL}deportivo.svg`, power: 66, stadium: "Риасор", played: false},
]

export const players = [
    {name: "Мбаппе", lastName: "Килиан", nation: "Франция", number: 10, age: 27, salary: 30, price: 180, power: 91, imgUrl: `${import.meta.env.BASE_URL}players4/mbappe.png`, position: "ФР", lineUp: "Основной состав"},
    {name: "Куртуа", lastName: "Тибо", nation: "Бельгия", number: 1, age: 34, salary: 15, price: 20, power: 89, imgUrl: `${import.meta.env.BASE_URL}players4/curtuos.png`, position: "ВР", lineUp: "Основной состав"},
    {name: "Александер-Арнольд", lastName: "Трент", nation: "Англия", number: 12, age: 27, salary: 16, price: 70, power: 85, imgUrl: `${import.meta.env.BASE_URL}players4/trent.png`, position: "ПЗ", lineUp: "Игрок ротации"},
    {name: "Милитао", lastName: "Эдер", nation: "Бразилия", number: 3, age: 28, salary: 12, price: 55, power: 85, imgUrl: `${import.meta.env.BASE_URL}players4/militao.png`, position: "ЦЗ", lineUp: "Глубина состава"},
    {name: "Хёйсен", lastName: "Дин", nation: "Испания", number: 4, age: 21, salary: 8, price: 70, power: 83, imgUrl: `${import.meta.env.BASE_URL}players4/huijsen.png`, position: "ЦЗ", lineUp: "Основной состав"},
    {name: "Каррерас", lastName: "Альваро", nation: "Испания", number: 18, age: 23, salary: 7, price: 50, power: 82, imgUrl: `${import.meta.env.BASE_URL}players4/careras.png`, position: "ЛЗ", lineUp: "Запасной состав"},
    {name: "Чуамени", lastName: "Орельен", nation: "Франция", number: 14, age: 26, salary: 12, price: 80, power: 86, imgUrl: `${import.meta.env.BASE_URL}players4/tchaomeni.png`, position: "ОП", lineUp: "Игрок ротации"},
    {name: "Вальверде", lastName: "Федерико", nation: "Уругвай", number: 8, age: 28, salary: 15, price: 110, power: 88, imgUrl: `${import.meta.env.BASE_URL}players4/valverde.png`, position: "ЦП", lineUp: "Основной состав"},
    {name: "Беллингем", lastName: "Джуд", nation: "Англия", number: 5, age: 23, salary: 22, price: 170, power: 90, imgUrl: `${import.meta.env.BASE_URL}players4/bellingham.png`, position: "АП", lineUp: "Основной состав"},
    {name: "Гюлер", lastName: "Арда", nation: "Турция", number: 15, age: 21, salary: 6, price: 90, power: 84, imgUrl: `${import.meta.env.BASE_URL}players4/guler.png`, position: "ПВ", lineUp: "Основной состав"},
    {name: "Винисиус", lastName: "Жуниор", nation: "Бразилия", number: 7, age: 26, salary: 25, price: 150, power: 90, imgUrl: `${import.meta.env.BASE_URL}players4/vini.png`, position: "ЛВ", lineUp: "Основной состав"},
    {name: "Лунин", lastName: "Андрей", nation: "Украина", number: 13, age: 27, salary: 5, price: 20, power: 80, imgUrl: `${import.meta.env.BASE_URL}players4/lunin.png`, position: "ВР", lineUp: "Запасной состав"},
    {name: "Думфрис", lastName: "Дензел", nation: "Нидерланды", number: 24, age: 30, salary: 8, price: 30, power: 82, imgUrl: `${import.meta.env.BASE_URL}players4/dumfrius.png`, position: "ПЗ", lineUp: "Основной состав"},
    {name: "Рюдигер", lastName: "Антонио", nation: "Германия", number: 22, age: 33, salary: 12, price: 15, power: 83, imgUrl: `${import.meta.env.BASE_URL}players4/rudiger.png`, position: "ЦЗ", lineUp: "Запасной состав"},
    {name: "Конате", lastName: "Ибраима", nation: "Франция", number: 16, age: 27, salary: 14, price: 60, power: 85, imgUrl: `${import.meta.env.BASE_URL}players4/konate.png`, position: "ЦЗ", lineUp: "Основной состав"},
    {name: "Асенсио", lastName: "Рауль", nation: "Испания", number: 2, age: 23, salary: 3, price: 30, power: 78, imgUrl: `${import.meta.env.BASE_URL}players4/asensio.png`, position: "ЦЗ", lineUp: "Глубина состава"},
    {name: "Кукурелья", lastName: "Марк", nation: "Испания", number: 17, age: 28, salary: 9, price: 50, power: 83, imgUrl: `${import.meta.env.BASE_URL}players4/cucrella.png`, position: "ЛЗ", lineUp: "Основной состав"},
    {name: "Камавинга", lastName: "Эдуардо", nation: "Франция", number: 6, age: 23, salary: 12, price: 70, power: 84, imgUrl: `${import.meta.env.BASE_URL}players4/camavinga.png`, position: "ЦП", lineUp: "Игрок ротации"},
    {name: "Силва", lastName: "Бернарду", nation: "Португалия", number: 20, age: 32, salary: 14, price: 30, power: 85, imgUrl: `${import.meta.env.BASE_URL}players4/bernardo.png`, position: "ЦП", lineUp: "Основной состав"},
    {name: "Эспи", lastName: "Карл", nation: "Испания", number: 19, age: 21, salary: 4, price: 20, power: 79, imgUrl: `${import.meta.env.BASE_URL}players4/espi.png`, position: "ФР", lineUp: "Игрок ротации"},
    {name: "Диас", lastName: "Браим", nation: "Марокко", number: 21, age: 27, salary: 8, price: 40, power: 82, imgUrl: `${import.meta.env.BASE_URL}players4/brahim.png`, position: "АП", lineUp: "Запасной состав"},
    {name: "Родриго", lastName: "Гоэс", nation: "Бразилия", number: 11, age: 25, salary: 15, price: 90, power: 85, imgUrl: `${import.meta.env.BASE_URL}players4/rodrygo.png`, position: "ПВ", lineUp: "Глубина состава"},
    {name: "Диоманде", lastName: "Ян", nation: "Кот-д'Ивуар", number: 25, age: 19, salary: 5, price: 60, power: 79, imgUrl: `${import.meta.env.BASE_URL}players4/yan.png`, position: "ЛВ", lineUp: "Игрок ротации"},
    {name: "Эндрик", lastName: "Фелипе", nation: "Бразилия", number: 9, age: 20, salary: 6, price: 45, power: 78, imgUrl: `${import.meta.env.BASE_URL}players4/endrik.png`, position: "ФР", lineUp: "Глубина состава"},
]

export const staff = [
    {name: "Моуриньо", lastName: "Жозе", age: 63, role: "Главный тренер", salary: 12, power: 90},
    {name: "Тральян", lastName: "Жоао", age: 46, role: "Второй тренер", salary: 2, power: 82},
    {name: "Мачадо", lastName: "Педро", age: 45, role: "Ассистент тренера", salary: 1.5, power: 80},
    {name: "Хедира", lastName: "Сами", age: 39, role: "Ассистент тренера", salary: 1.5, power: 78},
    {name: "Сантуш", lastName: "Нуну", age: 53, role: "Тренер вратарей", salary: 1, power: 83},
    {name: "Диаш", lastName: "Антониу", age: 48, role: "Тренер по физподготовке", salary: 1, power: 84},
    {name: "Пинтус", lastName: "Антонио", age: 64, role: "Тренер по физподготовке", salary: 1.5, power: 88},
    {name: "Мерелья", lastName: "Роберто", age: 40, role: "Главный аналитик", salary: 0.8, power: 79},
]

export const stadiumUpgrades = [
    {name: "Трибуны", description: "+ вместимость и доход с билетов в день матча", level: 0, maxLevel: 5, price: 45, priceStep: 15, type: "income", multiplier: 1, multiplierStep: 0.1},
    {name: "Газон", description: "Меньше травм, лучше качество игры дома", level: 0, maxLevel: 5, price: 20, priceStep: 10, type: "fans", multiplier: 1, multiplierStep: 0.05},
    {name: "Крыша", description: "Концерты и события в любую погоду", level: 0, maxLevel: 5, price: 30, priceStep: 10, type: "income", multiplier: 1, multiplierStep: 0.1},
    {name: "VIP-ложи", description: "+ доход от премиальных билетов", level: 0, maxLevel: 5, price: 30, priceStep: 10, type: "income", multiplier: 1, multiplierStep: 0.1},
    {name: "Фан-шоп", description: "+ продажи мерча и узнаваемость", level: 0, maxLevel: 5, price: 6, priceStep: 3, type: "fans", multiplier: 1, multiplierStep: 0.1},
    {name: "Медицинский центр", description: "Быстрее восстановление после травм", level: 0, maxLevel: 5, price: 12, priceStep: 5, type: "fans", multiplier: 1, multiplierStep: 0.05},
    {name: "Тренировочная база", description: "+ рост рейтинга молодых игроков", level: 0, maxLevel: 5, price: 25, priceStep: 10, type: "income", multiplier: 1, multiplierStep: 0.05},
    {name: "Парковка и транспорт", description: "+ посещаемость и настроение фанатов", level: 0, maxLevel: 5, price: 4, priceStep: 2, type: "fans", multiplier: 1, multiplierStep: 0.05},
]

export const marketPlayers = [
    {name: "Холанд", lastName: "Эрлинг", nation: "Норвегия", club: "Манчестер Сити", league: "АПЛ", age: 26, salary: 28, price: 180, power: 91, position: "ФР", imgUrl: `${import.meta.env.BASE_URL}players4/haaland.png.png`},
    {name: "Ямаль", lastName: "Ламин", nation: "Испания", club: "Барселона", league: "Ла Лига", age: 19, salary: 20, price: 200, power: 91, position: "ПВ", imgUrl: `${import.meta.env.BASE_URL}players4/10-Lamine.png`},
    {name: "Педри", lastName: "Гонсалес", nation: "Испания", club: "Барселона", league: "Ла Лига", age: 23, salary: 18, price: 130, power: 89, position: "ЦП", imgUrl: `${import.meta.env.BASE_URL}players4/08-Pedri.png.webp`},
    {name: "Олисе", lastName: "Майкл", nation: "Франция", club: "Бавария", league: "Бундеслига", age: 24, salary: 14, price: 130, power: 88, position: "ПВ", imgUrl: `${import.meta.env.BASE_URL}players4/olise.png`},
    {name: "Мусиала", lastName: "Джамал", nation: "Германия", club: "Бавария", league: "Бундеслига", age: 23, salary: 16, price: 140, power: 88, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/musiala.png`},
    {name: "Сака", lastName: "Букайо", nation: "Англия", club: "Арсенал", league: "АПЛ", age: 25, salary: 16, price: 140, power: 88, position: "ПВ", imgUrl: `${import.meta.env.BASE_URL}players4/87fab49199d9-arsenalmenssquad26277bukayo-saka.png.avif`},
    {name: "Мартинес", lastName: "Лаутаро", nation: "Аргентина", club: "Интер", league: "Серия А", age: 29, salary: 15, price: 90, power: 88, position: "ФР", imgUrl: `${import.meta.env.BASE_URL}players4/Lautaro_2x.webp`},
    {name: "Палмер", lastName: "Коул", nation: "Англия", club: "Челси", league: "АПЛ", age: 24, salary: 15, price: 120, power: 87, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/3333x5000_Avatar_Image_Men_26_27_Palmer_SF_Home_26_27_RGB_cnce6g.webp`},

    {name: "Салиба", lastName: "Вильям", nation: "Франция", club: "Арсенал", league: "АПЛ", age: 25, salary: 10, price: 80, power: 85, position: "ЦЗ", imgUrl: `${import.meta.env.BASE_URL}players4/acb476e282e8-2-william-saliba.png.avif`},
    {name: "Фоден", lastName: "Фил", nation: "Англия", club: "Манчестер Сити", league: "АПЛ", age: 26, salary: 14, price: 80, power: 85, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/phil-foden-elec-bl.png.webp`},
    {name: "Фернандеш", lastName: "Бруну", nation: "Португалия", club: "Манчестер Юнайтед", league: "АПЛ", age: 32, salary: 14, price: 40, power: 85, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/media_102559977_102167101.jpg.webp`},
    {name: "Гвардиол", lastName: "Йошко", nation: "Хорватия", club: "Манчестер Сити", league: "АПЛ", age: 24, salary: 10, price: 70, power: 84, position: "ЛЗ", imgUrl: `${import.meta.env.BASE_URL}players4/josko-gvardiol-elec-bl.png.webp`},
    {name: "Роджерс", lastName: "Морган", nation: "Англия", club: "Астон Вилла", league: "АПЛ", age: 24, salary: 6, price: 70, power: 83, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/3333x5000_Avatar_Image_Men_26_27_Rogers.webp`},
    {name: "Аканджи", lastName: "Мануэль", nation: "Швейцария", club: "Интер", league: "Серия А", age: 31, salary: 8, price: 30, power: 83, position: "ЦЗ", imgUrl: `${import.meta.env.BASE_URL}players4/Akanji_2x.webp`},
    {name: "Шерки", lastName: "Райан", nation: "Франция", club: "Манчестер Сити", league: "АПЛ", age: 23, salary: 8, price: 55, power: 82, position: "АП", imgUrl: `${import.meta.env.BASE_URL}players4/rayan-cherki-elec-bl.png.webp`},
    {name: "Антони", lastName: "Матеус", nation: "Бразилия", club: "Бетис", league: "Ла Лига", age: 26, salary: 6, price: 30, power: 80, position: "ПВ", imgUrl: `${import.meta.env.BASE_URL}players4/667430.jpg`},
]
